CREATE DATABASE inventario_beauty;
USE inventario_beauty;

CREATE TABLE roles (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50)
);

INSERT INTO roles (name) VALUES ('CLIENTE'), ('TRABAJADOR'), ('ADMIN');

CREATE TABLE users (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100),
password VARCHAR(255),
role_id BIGINT,
FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE products (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
price DOUBLE,
stock INT
);